ALTER TABLE tasks
    ADD COLUMN plane_x BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN plane_y BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN task_route TEXT NOT NULL DEFAULT '[]',
    ADD COLUMN is_accepted BOOLEAN NOT NULL DEFAULT FALSE;